*********************************************************************************************
* FUZZY ADDRESS CLEANING BEFORE NCOA/CASS ***************************************************
*******************************************************************************************;;
PROC SORT DATA = SERV.SERVICE3; BY VIN DESCENDING RO_DATE; RUN;

DATA SERV.SERVICE3;
	SET SERV.SERVICE3;
BY VIN;
	RETAIN ADDRESS_MATCH;
IF FIRST.VIN THEN DO;
	ADDRESS_MATCH = ADDRESS;** SET RETAIN VARIABLE **;
	ADDR_SCORE = .;
	OUTPUT;
END;	
ELSE DO;
	CALL COMPCOST('APPEND=',10,'TRUNCATE=',10,'DOUBLE=',25,'SINGLE=',25,'SWAP=',25,'PUNCTUATION=',10);
 	ADDR_SCORE = COMPGED(ADDRESS, ADDRESS_MATCH);
		ADDRESS_MATCH = ADDRESS;** UPDATE TO NEW ADDRESS **;
		OUTPUT;
	END;
RUN;

DATA SERV.SERVICE3;
      SET SERV.SERVICE3;
      BY VIN;
	  RETAIN PREV_ADDRESS FINAL_ADDRESS;
	IF FIRST.VIN THEN DO;
		FINAL_ADDRESS = ADDRESS;
		PREV_ADDRESS = ADDRESS;
	END;
	ELSE DO;
		IF ADDR_SCORE < 250 THEN DO;
			FINAL_ADDRESS = PREV_ADDRESS; 
		END;
		ELSE DO;
			 FINAL_ADDRESS = ADDRESS;
			 PREV_ADDRESS = ADDRESS;
		END;
	END;
	DROP PREV_ADDRESS ADDRESS_MATCH;
RUN;

/*optional future step... *** DO FUZZY MATCHING TO CLEAN FIRST & LAST NAMEs ***;*/
